Refine demo for Electron/Lua App
daurnimator/fengari-electron-example pull request #1
Opened 2019-12-16 15:09 UTC by thetrung

A more detailed instruction and update package.json to build and run electron app with Lua.

I'm really grateful to find your excellent work that allow me to work with Lua again on Electron/JS stuff ! Hope this to be helpful for other newbies and Fangari !

Cheers !

2019-12-16 15:26 UTC, daurnimator requested changes

2019-12-16 15:26 UTC, daurnimator commented on README.md
> +git clone https://github.com/thetrung/fengari-electron-example.git
You don't want this in the PR I assume

2019-12-16 15:26 UTC, daurnimator commented on README.md
> +npm install
FWIW I install `electron` via my disto package manager. Maybe put in different section?

2019-12-17 09:32 UTC, thetrung commented
Oops... my bad :)) Sorry, no intention. Was just pasting link.

2019-12-17 09:36 UTC, closed without merging